const cardsData = [
    {
        "id":  "1",
        "action":  "LikeForEach",
        "giftId":  "",
        "giftName":  "Team plants likes",
        "funcName":  "Spawn Blazer Snipea (1167)",
        "funcImg":  "images/game-icons/pvz/spawn_fire_sniper.webp",
        "trigImg":  "images/trig_7.svg",
        "triggerValue":  "50",
        "commands":  "spawn_fire_sniper",
        "repetition":  1
    },
    {
        "id":  "2",
        "action":  "LikeForEach",
        "giftId":  "",
        "giftName":  "Team zombies likes",
        "funcName":  "Spawn Trident Jugger-nut Gargantuar (240)",
        "funcImg":  "http://localhost:8080/images/game-icons/pvz/spawn_hydrofowl_zombie.webp",
        "trigImg":  "images/trig_7.svg",
        "triggerValue":  "50",
        "commands":  "spawn_hydrofowl_zombie",
        "repetition":  5
    },
    {
        "id":  "3",
        "action":  "LikeAmount",
        "giftId":  "",
        "giftName":  "Total Likes",
        "funcName":  "Spawn UltimateHorse",
        "funcImg":  "images/game-icons/pvz/spawn_ultimatehorse.webp",
        "trigImg":  "images/trig_7.svg",
        "triggerValue":  "50000",
        "commands":  "spawn_ultimatehorse",
        "repetition":  20
    },
    {
        "id":  "4",
        "action":  "Follow",
        "giftId":  "",
        "giftName":  "Follower",
        "funcName":  "Spawn SummonedHorse",
        "funcImg":  "images/game-icons/pvz/spawn_summonedhorse.webp",
        "trigImg":  "images/trig_1.svg",
        "triggerValue":  "",
        "commands":  "spawn_summonedhorse",
        "repetition":  20
    },
    {
        "id":  "5",
        "action":  "SelectedGift",
        "giftId":  "5655",
        "giftName":  "Rose",
        "funcName":  "Spawn Ultimate Football Zombie",
        "funcImg":  "images/game-icons/pvz/spawn_ultimate_football_zombie.webp",
        "trigImg":  "images/tiktok-gifts/5655_rose.webp",
        "triggerValue":  "",
        "commands":  "spawn_ultimate_football_zombie",
        "repetition":  1
    },
    {
        "id":  "6",
        "action":  "SelectedGift",
        "giftId":  "6788",
        "giftName":  "Glow Stick",
        "funcName":  "Spawn SummonedHorse",
        "funcImg":  "images/game-icons/pvz/spawn_summonedhorse.webp",
        "trigImg":  "images/tiktok-gifts/6788_glow_stick.webp",
        "triggerValue":  "",
        "commands":  "spawn_summonedhorse",
        "repetition":  5
    },
    {
        "id":  "7",
        "action":  "SelectedGift",
        "giftId":  "1228602",
        "giftName":  "GOten",
        "funcName":  "Ultimate Gold Gargantuar",
        "funcImg":  "http://localhost:8080/images/game-icons/pvz/spawn_squalour_zombie.webp",
        "trigImg":  "images/tiktok-gifts/1228602_goten.webp",
        "triggerValue":  "",
        "commands":  "ultimate_gold_gargantuar",
        "repetition":  5
    },
    {
        "id":  "8",
        "action":  "SelectedGift",
        "giftId":  "19441",
        "giftName":  "Freestyle",
        "funcName":  "Spawn EternalZombie_c",
        "funcImg":  "images/game-icons/pvz/spawn_eternalzombie_c.webp",
        "trigImg":  "images/tiktok-gifts/19441_freestyle.webp",
        "triggerValue":  "",
        "commands":  "spawn_eternalzombie_c",
        "repetition":  2
    },
    {
        "id":  "9",
        "action":  "SelectedGift",
        "giftId":  "231956",
        "giftName":  "Clap Clap",
        "funcName":  "Spawn Lost Penguin",
        "funcImg":  "images/game-icons/pvz/spawn_lost_penguin.webp",
        "trigImg":  "images/tiktok-gifts/231956_clap_clap.webp",
        "triggerValue":  "",
        "commands":  "spawn_lost_penguin",
        "repetition":  4
    },
    {
        "id":  "10",
        "action":  "SelectedGift",
        "giftId":  "6064",
        "giftName":  "GG",
        "funcName":  "Spawn Squalour Zombie",
        "funcImg":  "http://localhost:8080/images/game-icons/pvz/spawn_super_kirov.webp",
        "trigImg":  "images/tiktok-gifts/6064_gg.webp",
        "triggerValue":  "",
        "commands":  "spawn_squalour_zombie",
        "repetition":  1
    },
    {
        "id":  "11",
        "action":  "SelectedGift",
        "giftId":  "19447",
        "giftName":  "Overreact",
        "funcName":  "Spawn Jackson_c",
        "funcImg":  "images/game-icons/pvz/spawn_jackson_c.webp",
        "trigImg":  "images/tiktok-gifts/19447_overreact.webp",
        "triggerValue":  "",
        "commands":  "spawn_jackson_c",
        "repetition":  2
    },
    {
        "id":  "12",
        "action":  "SelectedGift",
        "giftId":  "9005",
        "giftName":  "Rafflesia",
        "funcName":  "Spawn Lost Snow Monster",
        "funcImg":  "images/game-icons/pvz/spawn_lost_snow_monster.webp",
        "trigImg":  "images/tiktok-gifts/9005_rafflesia.webp",
        "triggerValue":  "",
        "commands":  "spawn_lost_snow_monster",
        "repetition":  5
    },
    {
        "id":  "13",
        "action":  "SelectedGift",
        "giftId":  "12963",
        "giftName":  "Shining Starlight",
        "funcName":  "Spawn Lost Machine IV",
        "funcImg":  "images/game-icons/pvz/spawn_lost_machine_iv.webp",
        "trigImg":  "images/tiktok-gifts/12963_shining_starlight.webp",
        "triggerValue":  "",
        "commands":  "spawn_lost_machine_iv",
        "repetition":  5
    },
    {
        "id":  "14",
        "action":  "SelectedGift",
        "giftId":  "1402661",
        "giftName":  "Star Light",
        "funcName":  "Spawn Lost Machine III",
        "funcImg":  "images/game-icons/pvz/spawn_lost_machine_iii.webp",
        "trigImg":  "images/tiktok-gifts/1402661_star_light.webp",
        "triggerValue":  "",
        "commands":  "spawn_lost_machine_iii",
        "repetition":  20
    },
    {
        "id":  "15",
        "action":  "SelectedGift",
        "giftId":  "5487",
        "giftName":  "Finger Heart",
        "funcName":  "Spawn UltimateDolphin",
        "funcImg":  "images/game-icons/pvz/spawn_ultimatedolphin.webp",
        "trigImg":  "images/tiktok-gifts/5487_finger_heart.webp",
        "triggerValue":  "",
        "commands":  "spawn_ultimatedolphin",
        "repetition":  1
    },
    {
        "id":  "16",
        "action":  "SelectedGift",
        "giftId":  "19445",
        "giftName":  "Name shoutout",
        "funcName":  "Spawn Ultimate Jackbox Zombie",
        "funcImg":  "images/game-icons/pvz/spawn_ultimate_jackbox_zombie.webp",
        "trigImg":  "images/tiktok-gifts/19445_name_shoutout.webp",
        "triggerValue":  "",
        "commands":  "spawn_ultimate_jackbox_zombie",
        "repetition":  2
    },
    {
        "id":  "17",
        "action":  "SelectedGift",
        "giftId":  "544253",
        "giftName":  "I Like What I See",
        "funcName":  "Spawn HorseBoss",
        "funcImg":  "images/game-icons/pvz/spawn_horseboss.webp",
        "trigImg":  "images/tiktok-gifts/544253_i_like_what_i_see.webp",
        "triggerValue":  "",
        "commands":  "spawn_horseboss",
        "repetition":  5
    },
    {
        "id":  "18",
        "action":  "SelectedGift",
        "giftId":  "5779",
        "giftName":  "I love you",
        "funcName":  "Spawn Ultimate Paper Zombie",
        "funcImg":  "images/game-icons/pvz/spawn_ultimate_paper_zombie.webp",
        "trigImg":  "images/tiktok-gifts/5779_i_love_you.webp",
        "triggerValue":  "",
        "commands":  "spawn_ultimate_paper_zombie",
        "repetition":  3
    },
    {
        "id":  "19",
        "action":  "SelectedGift",
        "giftId":  "8913",
        "giftName":  "Rosa",
        "funcName":  "Spawn UltimateSwordZombie",
        "funcImg":  "images/game-icons/pvz/spawn_ultimateswordzombie.webp",
        "trigImg":  "images/tiktok-gifts/8913_rosa.webp",
        "triggerValue":  "",
        "commands":  "spawn_ultimateswordzombie",
        "repetition":  10
    },
    {
        "id":  "20",
        "action":  "SelectedGift",
        "giftId":  "19448",
        "giftName":  "Slow motion",
        "funcName":  "Spawn Jackson Driver Boss",
        "funcImg":  "images/game-icons/pvz/spawn_jackson_driver_boss.webp",
        "trigImg":  "images/tiktok-gifts/19448_slow_motion.webp",
        "triggerValue":  "",
        "commands":  "spawn_jackson_driver_boss",
        "repetition":  10
    },
    {
        "id":  "21",
        "action":  "SelectedGift",
        "giftId":  "15063",
        "giftName":  "Journey Pass",
        "funcName":  "Spawn UltimateEndoflameZombie",
        "funcImg":  "images/game-icons/pvz/spawn_ultimateendoflamezombie.webp",
        "trigImg":  "images/tiktok-gifts/15063_journey_pass.webp",
        "triggerValue":  "",
        "commands":  "spawn_ultimateendoflamezombie",
        "repetition":  1
    },
    {
        "id":  "22",
        "action":  "SelectedGift",
        "giftId":  "626056",
        "giftName":  "Kudos for My Star",
        "funcName":  "Spawn Submarine_c2",
        "funcImg":  "http://localhost:8080/images/game-icons/pvz/spawn_submarine_c2.webp",
        "trigImg":  "images/tiktok-gifts/626056_kudos_for_my_star.webp",
        "triggerValue":  "",
        "commands":  "spawn_submarine_c2;spawn_ultimate_machine_nut_zombie",
        "repetition":  3
    },
    {
        "id":  "23",
        "action":  "SelectedGift",
        "giftId":  "1298087",
        "giftName":  "Blossom Po",
        "funcName":  "Spawn Kirov_c",
        "funcImg":  "images/game-icons/pvz/spawn_kirov_c.webp",
        "trigImg":  "images/tiktok-gifts/1298087_blossom_po.webp",
        "triggerValue":  "",
        "commands":  "spawn_kirov_c",
        "repetition":  30
    },
    {
        "id":  "24",
        "action":  "SelectedGift",
        "giftId":  "626064",
        "giftName":  "G.O.A.T. Busker",
        "funcName":  "Spawn UltimateSnowZombie",
        "funcImg":  "images/game-icons/pvz/spawn_ultimatesnowzombie.webp",
        "trigImg":  "images/tiktok-gifts/626064_g_o_a_t__busker.webp",
        "triggerValue":  "",
        "commands":  "spawn_ultimatesnowzombie",
        "repetition":  30
    },
    {
        "id":  "25",
        "action":  "SelectedGift",
        "giftId":  "6427",
        "giftName":  "Hat and Mustache",
        "funcName":  "Spawn Ultimate Machine Nut Zombie",
        "funcImg":  "images/game-icons/pvz/spawn_ultimate_machine_nut_zombie.webp",
        "trigImg":  "images/tiktok-gifts/6427_hat_and_mustache.webp",
        "triggerValue":  "",
        "commands":  "spawn_ultimate_machine_nut_zombie",
        "repetition":  50
    },
    {
        "id":  "26",
        "action":  "SelectedGift",
        "giftId":  "5509",
        "giftName":  "Sunglasses",
        "funcName":  "Spawn Golden Zomboss",
        "funcImg":  "images/game-icons/pvz/spawn_zombie_boss2.webp",
        "trigImg":  "images/tiktok-gifts/5509_sunglasses.webp",
        "triggerValue":  "",
        "commands":  "spawn_zombie_boss2",
        "repetition":  30
    },
    {
        "id":  "27",
        "action":  "SelectedGift",
        "giftId":  "14557",
        "giftName":  "Puppy Kisses",
        "funcName":  "Kill all Plants",
        "funcImg":  "images/game-icons/pvz/kill_all_plants.webp",
        "trigImg":  "images/tiktok-gifts/14557_puppy_kisses.webp",
        "triggerValue":  "",
        "commands":  "kill_all_plants",
        "repetition":  1
    },
    {
        "id":  "28",
        "action":  "SelectedGift",
        "giftId":  "6267",
        "giftName":  "Corgi",
        "funcName":  "Spawn UltimateHorse",
        "funcImg":  "images/game-icons/pvz/spawn_ultimatehorse.webp",
        "trigImg":  "images/tiktok-gifts/6267_corgi.webp",
        "triggerValue":  "",
        "commands":  "spawn_ultimatehorse",
        "repetition":  50
    },
    {
        "id":  "29",
        "action":  "SelectedGift",
        "giftId":  "657072",
        "giftName":  "Galaxy\u0027s Bestest",
        "funcName":  "Spawn UltimateImpKing",
        "funcImg":  "images/game-icons/pvz/spawn_ultimateimpking.webp",
        "trigImg":  "images/tiktok-gifts/657072_galaxy_s_bestest.webp",
        "triggerValue":  "",
        "commands":  "spawn_ultimateimpking",
        "repetition":  100
    },
    {
        "id":  "30",
        "action":  "SelectedGift",
        "giftId":  "7168",
        "giftName":  "Money Gun",
        "funcName":  "Spawn UltimateHorse",
        "funcImg":  "images/game-icons/pvz/spawn_ultimatehorse.webp",
        "trigImg":  "images/tiktok-gifts/7168_money_gun.webp",
        "triggerValue":  "",
        "commands":  "spawn_ultimatehorse",
        "repetition":  100
    },
    {
        "id":  "31",
        "action":  "SelectedGift",
        "giftId":  "11046",
        "giftName":  "Galaxy",
        "funcName":  "Spawn UltimateImpKing",
        "funcImg":  "images/game-icons/pvz/spawn_ultimateimpking.webp",
        "trigImg":  "images/tiktok-gifts/11046_galaxy.webp",
        "triggerValue":  "",
        "commands":  "spawn_ultimateimpking",
        "repetition":  500
    },
    {
        "id":  "32",
        "action":  "SelectedGift",
        "giftId":  "7934",
        "giftName":  "Heart Me",
        "funcName":  "Spawn Big Sun Nut",
        "funcImg":  "images/game-icons/pvz/spawn_big_sun_nut.webp",
        "trigImg":  "images/tiktok-gifts/7934_heart_me.webp",
        "triggerValue":  "",
        "commands":  "spawn_big_sun_nut",
        "repetition":  50
    },
    {
        "id":  "33",
        "action":  "SelectedGift",
        "giftId":  "5269",
        "giftName":  "TikTok",
        "funcName":  "Charm all zombies",
        "funcImg":  "images/game-icons/pvz/charm_all_zombies.webp",
        "trigImg":  "images/tiktok-gifts/5269_tiktok.webp",
        "triggerValue":  "",
        "commands":  "charm_all_zombies",
        "repetition":  1
    },
    {
        "id":  "34",
        "action":  "SelectedGift",
        "giftId":  "5583",
        "giftName":  "Fire",
        "funcName":  "Spawn Super Threepeater",
        "funcImg":  "images/game-icons/pvz/spawn_superthreepeater.webp",
        "trigImg":  "images/tiktok-gifts/5583_fire.webp",
        "triggerValue":  "",
        "commands":  "spawn_superthreepeater",
        "repetition":  5
    },
    {
        "id":  "35",
        "action":  "SelectedGift",
        "giftId":  "19438",
        "giftName":  "Pop",
        "funcName":  "Spawn Dragon Pot",
        "funcImg":  "images/game-icons/pvz/spawn_dragon_pot.webp",
        "trigImg":  "images/tiktok-gifts/19438_pop.webp",
        "triggerValue":  "",
        "commands":  "spawn_dragon_pot",
        "repetition":  6
    },
    {
        "id":  "36",
        "action":  "SelectedGift",
        "giftId":  "6784",
        "giftName":  "Cake Slice",
        "funcName":  "Spawn Ultimate Spruce",
        "funcImg":  "images/game-icons/pvz/spawn_ultimate_spruce.webp",
        "trigImg":  "images/tiktok-gifts/6784_cake_slice.webp",
        "triggerValue":  "",
        "commands":  "spawn_ultimate_spruce",
        "repetition":  6
    },
    {
        "id":  "37",
        "action":  "SelectedGift",
        "giftId":  "231955",
        "giftName":  "Good Job",
        "funcName":  "Spawn Ultimate Corn",
        "funcImg":  "images/game-icons/pvz/spawn_ultimate_corn.webp",
        "trigImg":  "images/tiktok-gifts/231955_good_job.webp",
        "triggerValue":  "",
        "commands":  "spawn_ultimate_corn",
        "repetition":  2
    },
    {
        "id":  "38",
        "action":  "SelectedGift",
        "giftId":  "919346",
        "giftName":  "Welcome Dallah",
        "funcName":  "Spawn Ultimate Gloom",
        "funcImg":  "images/game-icons/pvz/spawn_ultimate_gloom.webp",
        "trigImg":  "images/tiktok-gifts/919346_welcome_dallah.webp",
        "triggerValue":  "",
        "commands":  "spawn_ultimate_gloom",
        "repetition":  1
    },
    {
        "id":  "39",
        "action":  "SelectedGift",
        "giftId":  "19439",
        "giftName":  "Oldies",
        "funcName":  "Spawn UltimateCabbageCannon",
        "funcImg":  "images/game-icons/pvz/spawn_ultimatecabbagecannon.webp",
        "trigImg":  "images/tiktok-gifts/19439_oldies.webp",
        "triggerValue":  "",
        "commands":  "spawn_ultimatecabbagecannon",
        "repetition":  6
    },
    {
        "id":  "40",
        "action":  "SelectedGift",
        "giftId":  "19446",
        "giftName":  "Wink wink",
        "funcName":  "Spawn Ultimate Holy Star",
        "funcImg":  "http://localhost:8080/images/game-icons/pvz/spawn_ultimate_holy_star.webp",
        "trigImg":  "images/tiktok-gifts/19446_wink_wink.webp",
        "triggerValue":  "",
        "commands":  "spawn_ultimate_holy_star",
        "repetition":  1
    },
    {
        "id":  "41",
        "action":  "SelectedGift",
        "giftId":  "13651",
        "giftName":  "Go Popular",
        "funcName":  "Spawn Ultimate Chomper",
        "funcImg":  "images/game-icons/pvz/spawn_ultimate_chomper.webp",
        "trigImg":  "images/tiktok-gifts/13651_go_popular.webp",
        "triggerValue":  "",
        "commands":  "spawn_ultimate_chomper",
        "repetition":  1
    },
    {
        "id":  "42",
        "action":  "SelectedGift",
        "giftId":  "15232",
        "giftName":  "You\u0027re awesome",
        "funcName":  "Spawn DoomSniper",
        "funcImg":  "images/game-icons/pvz/spawn_doomsniper.webp",
        "trigImg":  "images/tiktok-gifts/15232_you_re_awesome.webp",
        "triggerValue":  "",
        "commands":  "spawn_doomsniper",
        "repetition":  6
    },
    {
        "id":  "43",
        "action":  "SelectedGift",
        "giftId":  "1167769",
        "giftName":  "Mate Melody",
        "funcName":  "Spawn Magic Snow Pea2",
        "funcImg":  "images/game-icons/pvz/spawn_magic_snow_pea2.webp",
        "trigImg":  "images/tiktok-gifts/1167769_mate_melody.webp",
        "triggerValue":  "",
        "commands":  "spawn_magic_snow_pea2",
        "repetition":  6
    },
    {
        "id":  "44",
        "action":  "SelectedGift",
        "giftId":  "15231",
        "giftName":  "Love you so much",
        "funcName":  "Spawn SuperNutShooter",
        "funcImg":  "images/game-icons/pvz/spawn_supernutshooter.webp",
        "trigImg":  "images/tiktok-gifts/15231_love_you_so_much.webp",
        "triggerValue":  "",
        "commands":  "spawn_supernutshooter",
        "repetition":  2
    },
    {
        "id":  "45",
        "action":  "SelectedGift",
        "giftId":  "118812",
        "giftName":  "Divine Fingers",
        "funcName":  "Spawn Bedrock Tall Nut",
        "funcImg":  "images/game-icons/pvz/spawn_bedrocktallnut.webp",
        "trigImg":  "images/tiktok-gifts/118812_divine_fingers.webp",
        "triggerValue":  "",
        "commands":  "spawn_bedrocktallnut",
        "repetition":  6
    },
    {
        "id":  "46",
        "action":  "SelectedGift",
        "giftId":  "919386",
        "giftName":  "Love in Scent",
        "funcName":  "Spawn UltimateBamboo",
        "funcImg":  "images/game-icons/pvz/spawn_ultimatebamboo.webp",
        "trigImg":  "images/tiktok-gifts/919386_love_in_scent.webp",
        "triggerValue":  "",
        "commands":  "spawn_ultimatebamboo",
        "repetition":  6
    },
    {
        "id":  "47",
        "action":  "SelectedGift",
        "giftId":  "105781",
        "giftName":  "Spinning Soccer",
        "funcName":  "Spawn UltimateSeaShroom",
        "funcImg":  "images/game-icons/pvz/spawn_ultimateseashroom.webp",
        "trigImg":  "images/tiktok-gifts/105781_spinning_soccer.webp",
        "triggerValue":  "",
        "commands":  "spawn_ultimateseashroom",
        "repetition":  6
    },
    {
        "id":  "48",
        "action":  "SelectedGift",
        "giftId":  "1137702",
        "giftName":  "Encore Ticket",
        "funcName":  "Spawn Super Threepeater SP (Phoenix)",
        "funcImg":  "images/game-icons/pvz/spawn_superthreepeater_sp.webp",
        "trigImg":  "images/tiktok-gifts/1137702_encore_ticket.webp",
        "triggerValue":  "",
        "commands":  "spawn_superthreepeater_sp",
        "repetition":  6
    },
    {
        "id":  "49",
        "action":  "SelectedGift",
        "giftId":  "9947",
        "giftName":  "Friendship Necklace",
        "funcName":  "Spawn NuclearDoomCherry",
        "funcImg":  "images/game-icons/pvz/spawn_nucleardoomcherry.webp",
        "trigImg":  "images/tiktok-gifts/9947_friendship_necklace.webp",
        "triggerValue":  "",
        "commands":  "spawn_nucleardoomcherry",
        "repetition":  3
    },
    {
        "id":  "50",
        "action":  "SelectedGift",
        "giftId":  "15328",
        "giftName":  "Fried Chicken",
        "funcName":  "Spawn Ultimate Spring",
        "funcImg":  "images/game-icons/pvz/spawn_ultimate_spring.webp",
        "trigImg":  "images/tiktok-gifts/15328_fried_chicken.webp",
        "triggerValue":  "",
        "commands":  "spawn_ultimate_spring",
        "repetition":  10
    },
    {
        "id":  "51",
        "action":  "SelectedGift",
        "giftId":  "919332",
        "giftName":  "Mystic Ney",
        "funcName":  "Spawn UltimateJalaNut",
        "funcImg":  "images/game-icons/pvz/spawn_ultimatejalanut.webp",
        "trigImg":  "images/tiktok-gifts/919332_mystic_ney.webp",
        "triggerValue":  "",
        "commands":  "spawn_ultimatejalanut",
        "repetition":  100
    },
    {
        "id":  "52",
        "action":  "SelectedGift",
        "giftId":  "13215",
        "giftName":  "Night Star",
        "funcName":  "Spawn UltimateSunNut",
        "funcImg":  "images/game-icons/pvz/spawn_ultimatesunnut.webp",
        "trigImg":  "images/tiktok-gifts/13215_night_star.webp",
        "triggerValue":  "",
        "commands":  "spawn_ultimatesunnut",
        "repetition":  100
    },
    {
        "id":  "53",
        "action":  "SelectedGift",
        "giftId":  "9465",
        "giftName":  "Fruit Friends",
        "funcName":  "Spawn Cherry Jalapeno",
        "funcImg":  "images/game-icons/pvz/spawn_cherry_jalapeno.webp",
        "trigImg":  "images/tiktok-gifts/9465_fruit_friends.webp",
        "triggerValue":  "",
        "commands":  "spawn_cherry_jalapeno",
        "repetition":  500
    },
    {
        "id":  "54",
        "action":  "SelectedGift",
        "giftId":  "6007",
        "giftName":  "Boxing Gloves",
        "funcName":  "Spawn NuclearDoomCherry",
        "funcImg":  "images/game-icons/pvz/spawn_nucleardoomcherry.webp",
        "trigImg":  "images/tiktok-gifts/6007_boxing_gloves.webp",
        "triggerValue":  "",
        "commands":  "spawn_nucleardoomcherry",
        "repetition":  500
    },
    {
        "id":  "55",
        "action":  "SelectedGift",
        "giftId":  "15382",
        "giftName":  "LIVE Ranking Crown",
        "funcName":  "Kill all Zombies",
        "funcImg":  "images/game-icons/pvz/kill_all_zombies.webp",
        "trigImg":  "images/tiktok-gifts/15382_live_ranking_crown.webp",
        "triggerValue":  "",
        "commands":  "kill_all_zombies",
        "repetition":  1
    },
    {
        "id":  "56",
        "action":  "SelectedGift",
        "giftId":  "231958",
        "giftName":  "Mind Blown",
        "funcName":  "Start LawnMower",
        "funcImg":  "images/game-icons/pvz/start_lawnmower.webp",
        "trigImg":  "images/tiktok-gifts/231958_mind_blown.webp",
        "triggerValue":  "",
        "commands":  "start_lawnmower",
        "repetition":  1
    },
    {
        "id":  "57",
        "action":  "SelectedGift",
        "giftId":  "231957",
        "giftName":  "Intimacy",
        "funcName":  "Restart LawnMower",
        "funcImg":  "images/game-icons/pvz/restart_lawnmower.webp",
        "trigImg":  "images/tiktok-gifts/231957_intimacy.webp",
        "triggerValue":  "",
        "commands":  "restart_lawnmower",
        "repetition":  1
    },
    {
        "id":  "58",
        "action":  "SelectedGift",
        "giftId":  "1137734",
        "giftName":  "I\u0027m Yours",
        "funcName":  "Delete LawnMower",
        "funcImg":  "images/game-icons/pvz/delete_lawnmower.webp",
        "trigImg":  "images/tiktok-gifts/1137734_i_m_yours.webp",
        "triggerValue":  "",
        "commands":  "delete_lawnmower",
        "repetition":  1
    },
    {
        "id":  "59",
        "action":  "Share",
        "giftId":  "",
        "giftName":  "Share Stream",
        "funcName":  "Plant everywahre",
        "funcImg":  "images/game-icons/pvz/plant_everywahre.webp",
        "trigImg":  "images/trig_1.svg",
        "triggerValue":  "",
        "commands":  "plant_everywahre",
        "repetition":  1
    },
    {
        "id":  "60",
        "action":  "SelectedGift",
        "giftId":  "5879",
        "giftName":  "Doughnut",
        "funcName":  "Spawn Golden Zomboss",
        "funcImg":  "images/game-icons/pvz/spawn_zombie_boss2.webp",
        "trigImg":  "images/tiktok-gifts/5879_doughnut.webp",
        "triggerValue":  "",
        "commands":  "spawn_zombie_boss2",
        "repetition":  1
    },
    {
        "id":  "61",
        "action":  "SelectedGift",
        "giftId":  "",
        "giftName":  "Select trigger",
        "funcName":  "Remove LawnMower",
        "funcImg":  "images/game-icons/pvz/remove_lawnmower.webp",
        "trigImg":  "images/tiktok-gifts/5655_rose.webp",
        "triggerValue":  "",
        "commands":  "remove_lawnmower",
        "repetition":  1
    },
    {
        "id":  "63",
        "action":  "SelectedGift",
        "giftId":  "19443",
        "giftName":  "Bravo!",
        "funcName":  "Spawn UltimateSniperGatling",
        "funcImg":  "images/game-icons/pvz/spawn_ultimatesnipergatling.webp",
        "trigImg":  "images/tiktok-gifts/19443_bravo.webp",
        "triggerValue":  "",
        "commands":  "spawn_ultimatesnipergatling",
        "repetition":  10
    },
    {
        "id":  "64",
        "action":  "SelectedGift",
        "giftId":  "16757",
        "giftName":  "Bibingka",
        "funcName":  "Spawn HorseZombie",
        "funcImg":  "images/game-icons/pvz/spawn_horsezombie.webp",
        "trigImg":  "images/tiktok-gifts/16757_bibingka.webp",
        "triggerValue":  "",
        "commands":  "spawn_horsezombie",
        "repetition":  1
    }
];