$s2eItems = @(
  # Photo 1 (1-30)
  @{ name = "Kill all Plants"; cmd = "kill_all_plants"; img = "images/game-icons/pvz/kill_all_plants.webp"; type = "power" },
  @{ name = "Kill all Zombies"; cmd = "kill_all_zombies"; img = "images/game-icons/pvz/kill_all_zombies.webp"; type = "power" },
  @{ name = "Double demage"; cmd = "double_demage"; img = "images/game-icons/pvz/double_demage.webp"; type = "power" },
  @{ name = "X100 demage"; cmd = "x100_demage"; img = "images/game-icons/pvz/x100_demage.webp"; type = "power" },
  @{ name = "Invulnerable zombies"; cmd = "invulnerable_zombies"; img = "images/game-icons/pvz/invulnerable_zombies.webp"; type = "power" },
  @{ name = "Invulnerable plants"; cmd = "invulnerable_plants"; img = "images/game-icons/pvz/invulnerable_plants.webp"; type = "power" },
  @{ name = "Sun"; cmd = "add_sun"; img = "images/game-icons/pvz/add_sun.webp"; type = "power" },
  @{ name = "Set Sun"; cmd = "set_sun"; img = "images/game-icons/pvz/set_sun.webp"; type = "power" },
  @{ name = "Unlimited Sun"; cmd = "unlimited_sun"; img = "images/game-icons/pvz/unlimited_sun.webp"; type = "power" },
  @{ name = "Free cooldown"; cmd = "free_cooldown"; img = "images/game-icons/pvz/free_cooldown.webp"; type = "power" },
  @{ name = "Seed rain"; cmd = "seed_rain"; img = "images/game-icons/pvz/seed_rain.webp"; type = "power" },
  @{ name = "Win level"; cmd = "win_level"; img = "images/game-icons/pvz/win_level.webp"; type = "power" },
  @{ name = "Spawn fertilizer"; cmd = "spawn_fertilizer"; img = "images/game-icons/pvz/spawn_fertilizer.webp"; type = "power" },
  @{ name = "Spawn bucket"; cmd = "spawn_bucket"; img = "images/game-icons/pvz/spawn_bucket.webp"; type = "power" },
  @{ name = "Spawn helmet"; cmd = "spawn_helmet"; img = "images/game-icons/pvz/spawn_helmet.webp"; type = "power" },
  @{ name = "Spawn jack"; cmd = "spawn_jack"; img = "images/game-icons/pvz/spawn_jack.webp"; type = "power" },
  @{ name = "Spawn pickaxe"; cmd = "spawn_pickaxe"; img = "images/game-icons/pvz/spawn_pickaxe.webp"; type = "power" },
  @{ name = "Spawn sprout"; cmd = "spawn_sprout"; img = "images/game-icons/pvz/spawn_sprout.webp"; type = "power" },
  @{ name = "Spawn mecha"; cmd = "spawn_mecha"; img = "images/game-icons/pvz/spawn_mecha.webp"; type = "power" },
  @{ name = "Spawn meteor"; cmd = "spawn_meteor"; img = "images/game-icons/pvz/spawn_meteor.webp"; type = "power" },
  @{ name = "Charm all zombies"; cmd = "charm_all_zombies"; img = "images/game-icons/pvz/charm_all_zombies.webp"; type = "power" },
  @{ name = "Spawn Peashooter"; cmd = "spawn_peashooter"; img = "images/game-icons/pvz/spawn_peashooter.webp"; type = "plant" },
  @{ name = "Spawn Cherry Bomb"; cmd = "spawn_cherry_bomb"; img = "images/game-icons/pvz/spawn_cherry_bomb.webp"; type = "plant" },
  @{ name = "Spawn Wall Nut"; cmd = "spawn_wall_nut"; img = "images/game-icons/pvz/spawn_wall_nut.webp"; type = "plant" },
  @{ name = "Spawn Potato Mine"; cmd = "spawn_potato_mine"; img = "images/game-icons/pvz/spawn_potato_mine.webp"; type = "plant" },
  @{ name = "Spawn Chomper"; cmd = "spawn_chomper"; img = "images/game-icons/pvz/spawn_chomper.webp"; type = "plant" },
  @{ name = "Spawn Small Puff"; cmd = "spawn_small_puff"; img = "images/game-icons/pvz/spawn_small_puff.webp"; type = "plant" },
  @{ name = "Spawn Fume Shroom"; cmd = "spawn_fume_shroom"; img = "images/game-icons/pvz/spawn_fume_shroom.webp"; type = "plant" },
  @{ name = "Spawn Hypno Shroom"; cmd = "spawn_hypno_shroom"; img = "images/game-icons/pvz/spawn_hypno_shroom.webp"; type = "plant" },
  @{ name = "Spawn Scaredy Shroom"; cmd = "spawn_scaredy_shroom"; img = "images/game-icons/pvz/spawn_scaredy_shroom.webp"; type = "plant" },

  # Photo 2 (31-60)
  @{ name = "Spawn Ice Shroom"; cmd = "spawn_ice_shroom"; img = "images/game-icons/pvz/spawn_ice_shroom.webp"; type = "plant" },
  @{ name = "Spawn Doom Shroom"; cmd = "spawn_doom_shroom"; img = "images/game-icons/pvz/spawn_doom_shroom.webp"; type = "plant" },
  @{ name = "Spawn Lily Pad"; cmd = "spawn_lily_pad"; img = "images/game-icons/pvz/spawn_lily_pad.webp"; type = "plant" },
  @{ name = "Spawn Squash"; cmd = "spawn_squash"; img = "images/game-icons/pvz/spawn_squash.webp"; type = "plant" },
  @{ name = "Spawn Three Peater"; cmd = "spawn_three_peater"; img = "images/game-icons/pvz/spawn_three_peater.webp"; type = "plant" },
  @{ name = "Spawn Jalapeno"; cmd = "spawn_jalapeno"; img = "images/game-icons/pvz/spawn_jalapeno.webp"; type = "plant" },
  @{ name = "Spawn Caltrop"; cmd = "spawn_caltrop"; img = "images/game-icons/pvz/spawn_caltrop.webp"; type = "plant" },
  @{ name = "Spawn Torch Wood"; cmd = "spawn_torch_wood"; img = "images/game-icons/pvz/spawn_torch_wood.webp"; type = "plant" },
  @{ name = "Spawn Sea Shroom"; cmd = "spawn_sea_shroom"; img = "images/game-icons/pvz/spawn_sea_shroom.webp"; type = "plant" },
  @{ name = "Spawn Plantern"; cmd = "spawn_plantern"; img = "images/game-icons/pvz/spawn_plantern.webp"; type = "plant" },
  @{ name = "Spawn Cactus"; cmd = "spawn_cactus"; img = "images/game-icons/pvz/spawn_cactus.webp"; type = "plant" },
  @{ name = "Spawn Blover"; cmd = "spawn_blover"; img = "images/game-icons/pvz/spawn_blover.webp"; type = "plant" },
  @{ name = "Spawn Star Fruit"; cmd = "spawn_star_fruit"; img = "images/game-icons/pvz/spawn_star_fruit.webp"; type = "plant" },
  @{ name = "Spawn Pumpkin"; cmd = "spawn_pumpkin"; img = "images/game-icons/pvz/spawn_pumpkin.webp"; type = "plant" },
  @{ name = "Spawn Magnetshroom"; cmd = "spawn_magnetshroom"; img = "images/game-icons/pvz/spawn_magnetshroom.webp"; type = "plant" },
  @{ name = "Spawn Cabbagepult"; cmd = "spawn_cabbagepult"; img = "images/game-icons/pvz/spawn_cabbagepult.webp"; type = "plant" },
  @{ name = "Spawn Pot"; cmd = "spawn_pot"; img = "images/game-icons/pvz/spawn_pot.webp"; type = "plant" },
  @{ name = "Spawn Cornpult"; cmd = "spawn_cornpult"; img = "images/game-icons/pvz/spawn_cornpult.webp"; type = "plant" },
  @{ name = "Spawn Garlic"; cmd = "spawn_garlic"; img = "images/game-icons/pvz/spawn_garlic.webp"; type = "plant" },
  @{ name = "Spawn Umbrellaleaf"; cmd = "spawn_umbrellaleaf"; img = "images/game-icons/pvz/spawn_umbrellaleaf.webp"; type = "plant" },
  @{ name = "Spawn Marigold"; cmd = "spawn_marigold"; img = "images/game-icons/pvz/spawn_marigold.webp"; type = "plant" },
  @{ name = "Spawn Melonpult"; cmd = "spawn_melonpult"; img = "images/game-icons/pvz/spawn_melonpult.webp"; type = "plant" },
  @{ name = "Spawn Shulkflower"; cmd = "spawn_shulkflower"; img = "images/game-icons/pvz/spawn_shulkflower.webp"; type = "plant" },
  @{ name = "Spawn Electric Onion"; cmd = "spawn_electric_onion"; img = "images/game-icons/pvz/spawn_electric_onion.webp"; type = "plant" },
  @{ name = "Spawn Ice Bean"; cmd = "spawn_ice_bean"; img = "images/game-icons/pvz/spawn_ice_bean.webp"; type = "plant" },
  @{ name = "Spawn Endo Flame Girl"; cmd = "spawn_endo_flame_girl"; img = "images/game-icons/pvz/spawn_endo_flame_girl.webp"; type = "plant" },
  @{ name = "Spawn Hamburger"; cmd = "spawn_hamburger"; img = "images/game-icons/pvz/spawn_hamburger.webp"; type = "plant" },
  @{ name = "Spawn Mix Bomb"; cmd = "spawn_mix_bomb"; img = "images/game-icons/pvz/spawn_mix_bomb.webp"; type = "plant" },
  @{ name = "Spawn Imitater"; cmd = "spawn_imitater"; img = "images/game-icons/pvz/spawn_imitater.webp"; type = "plant" },
  @{ name = "Spawn Squalour"; cmd = "spawn_squalour"; img = "images/game-icons/pvz/spawn_squalour.webp"; type = "plant" },

  # Photo 3 (61-90)
  @{ name = "Spawn Sword Star"; cmd = "spawn_sword_star"; img = "images/game-icons/pvz/spawn_sword_star.webp"; type = "plant" },
  @{ name = "Spawn Present Zombie"; cmd = "spawn_present_zombie"; img = "images/game-icons/pvz/spawn_present_zombie.webp"; type = "zombie" },
  @{ name = "Spawn Big Sun Nut"; cmd = "spawn_big_sun_nut"; img = "images/game-icons/pvz/spawn_big_sun_nut.webp"; type = "plant" },
  @{ name = "Spawn Cattail Girl"; cmd = "spawn_cattail_girl"; img = "images/game-icons/pvz/spawn_cattail_girl.webp"; type = "plant" },
  @{ name = "Spawn Wheat"; cmd = "spawn_wheat"; img = "images/game-icons/pvz/spawn_wheat.webp"; type = "plant" },
  @{ name = "Spawn Endo Flame"; cmd = "spawn_endo_flame"; img = "images/game-icons/pvz/spawn_endo_flame.webp"; type = "plant" },
  @{ name = "Spawn Big Wall Nut"; cmd = "spawn_big_wall_nut"; img = "images/game-icons/pvz/spawn_big_wall_nut.webp"; type = "plant" },
  @{ name = "Spawn Present"; cmd = "spawn_present"; img = "images/game-icons/pvz/spawn_present.webp"; type = "power" },
  @{ name = "Spawn Hypno Emperor"; cmd = "spawn_hypno_emperor"; img = "images/game-icons/pvz/spawn_hypno_emperor.webp"; type = "plant" },
  @{ name = "Spawn Ultimate Gatling"; cmd = "spawn_ultimate_gatling"; img = "images/game-icons/pvz/spawn_ultimate_gatling.webp"; type = "plant" },
  @{ name = "Spawn Ultimate Torch"; cmd = "spawn_ultimate_torch"; img = "images/game-icons/pvz/spawn_ultimate_torch.webp"; type = "plant" },
  @{ name = "Spawn Ultimate Chomper"; cmd = "spawn_ultimate_chomper"; img = "images/game-icons/pvz/spawn_ultimate_chomper.webp"; type = "plant" },
  @{ name = "Spawn Ultimate Fume"; cmd = "spawn_ultimate_fume"; img = "images/game-icons/pvz/spawn_ultimate_fume.webp"; type = "plant" },
  @{ name = "Spawn Super Sun Nut"; cmd = "spawn_super_sun_nut"; img = "images/game-icons/pvz/spawn_super_sun_nut.webp"; type = "plant" },
  @{ name = "Spawn Obsidian Spike"; cmd = "spawn_obsidian_spike"; img = "images/game-icons/pvz/spawn_obsidian_spike.webp"; type = "plant" },
  @{ name = "Spawn Doom Gatling"; cmd = "spawn_doom_gatling"; img = "images/game-icons/pvz/spawn_doom_gatling.webp"; type = "plant" },
  @{ name = "Spawn Snow Gatling Puff"; cmd = "spawn_snow_gatling_puff"; img = "images/game-icons/pvz/spawn_snow_gatling_puff.webp"; type = "plant" },
  @{ name = "Spawn Ultimate Star"; cmd = "spawn_ultimate_star"; img = "images/game-icons/pvz/spawn_ultimate_star.webp"; type = "plant" },
  @{ name = "Spawn Ultimate Gloom"; cmd = "spawn_ultimate_gloom"; img = "images/game-icons/pvz/spawn_ultimate_gloom.webp"; type = "plant" },
  @{ name = "Spawn Ultimate Pumpkin"; cmd = "spawn_ultimate_pumpkin"; img = "images/game-icons/pvz/spawn_ultimate_pumpkin.webp"; type = "plant" },
  @{ name = "Spawn Ultimate Fly"; cmd = "spawn_ultimate_fly"; img = "images/game-icons/pvz/spawn_ultimate_fly.webp"; type = "plant" },
  @{ name = "Spawn Ultimate Tall Nut"; cmd = "spawn_ultimate_tall_nut"; img = "images/game-icons/pvz/spawn_ultimate_tall_nut.webp"; type = "plant" },
  @{ name = "Spawn Ultimate Melon"; cmd = "spawn_ultimate_melon"; img = "images/game-icons/pvz/spawn_ultimate_melon.webp"; type = "plant" },
  @{ name = "Spawn Ultimate Cannon"; cmd = "spawn_ultimate_cannon"; img = "images/game-icons/pvz/spawn_ultimate_cannon.webp"; type = "plant" },
  @{ name = "Spawn Emerald Umbrella"; cmd = "spawn_emerald_umbrella"; img = "images/game-icons/pvz/spawn_emerald_umbrella.webp"; type = "plant" },
  @{ name = "Spawn Hypno Queen"; cmd = "spawn_hypno_queen"; img = "images/game-icons/pvz/spawn_hypno_queen.webp"; type = "plant" },
  @{ name = "Spawn Ash Three Peater"; cmd = "spawn_ash_three_peater"; img = "images/game-icons/pvz/spawn_ash_three_peater.webp"; type = "plant" },
  @{ name = "Spawn Super Three Peater"; cmd = "spawn_super_three_peater"; img = "images/game-icons/pvz/spawn_super_three_peater.webp"; type = "plant" },
  @{ name = "Spawn Ultimate Blover"; cmd = "spawn_ultimate_blover"; img = "images/game-icons/pvz/spawn_ultimate_blover.webp"; type = "plant" },
  @{ name = "Spawn Garlic Ultimate Chomper"; cmd = "spawn_garlic_ultimate_chomper"; img = "images/game-icons/pvz/spawn_garlic_ultimate_chomper.webp"; type = "plant" },

  # Photo 4 (91-120)
  @{ name = "Spawn Cherry Ultimate Pumpkin"; cmd = "spawn_cherry_ultimate_pumpkin"; img = "images/game-icons/pvz/spawn_cherry_ultimate_pumpkin.webp"; type = "plant" },
  @{ name = "Spawn Red Emerald Umbrella"; cmd = "spawn_red_emerald_umbrella"; img = "images/game-icons/pvz/spawn_red_emerald_umbrella.webp"; type = "plant" },
  @{ name = "Spawn Ultimate Hypno"; cmd = "spawn_ultimate_hypno"; img = "images/game-icons/pvz/spawn_ultimate_hypno.webp"; type = "plant" },
  @{ name = "Spawn Ultimate Potato Nut"; cmd = "spawn_ultimate_potato_nut"; img = "images/game-icons/pvz/spawn_ultimate_potato_nut.webp"; type = "plant" },
  @{ name = "Spawn Cattail Lour"; cmd = "spawn_cattail_lour"; img = "images/game-icons/pvz/spawn_cattail_lour.webp"; type = "plant" },
  @{ name = "Spawn Ultimate Big Gatling"; cmd = "spawn_ultimate_big_gatling"; img = "images/game-icons/pvz/spawn_ultimate_big_gatling.webp"; type = "plant" },
  @{ name = "Spawn Super Hypno Doom"; cmd = "spawn_super_hypno_doom"; img = "images/game-icons/pvz/spawn_super_hypno_doom.webp"; type = "plant" },
  @{ name = "Spawn Sun Gatling Puff"; cmd = "spawn_sun_gatling_puff"; img = "images/game-icons/pvz/spawn_sun_gatling_puff.webp"; type = "plant" },
  @{ name = "Spawn Gatling Doom Scaredy"; cmd = "spawn_gatling_doom_scaredy"; img = "images/game-icons/pvz/spawn_gatling_doom_scaredy.webp"; type = "plant" },
  @{ name = "Spawn Obsidian Wall Nut"; cmd = "spawn_obsidian_wall_nut"; img = "images/game-icons/pvz/spawn_obsidian_wall_nut.webp"; type = "plant" },
  @{ name = "Spawn Gold Three Torch"; cmd = "spawn_gold_three_torch"; img = "images/game-icons/pvz/spawn_gold_three_torch.webp"; type = "plant" },
  @{ name = "Spawn Ultimate Cactus"; cmd = "spawn_ultimate_cactus"; img = "images/game-icons/pvz/spawn_ultimate_cactus.webp"; type = "plant" },
  @{ name = "Spawn Ultimate Cabbage"; cmd = "spawn_ultimate_cabbage"; img = "images/game-icons/pvz/spawn_ultimate_cabbage.webp"; type = "plant" },
  @{ name = "Spawn I F V Pumpkin"; cmd = "spawn_i_f_v_pumpkin"; img = "images/game-icons/pvz/spawn_i_f_v_pumpkin.webp"; type = "plant" },
  @{ name = "Spawn Solar Pot"; cmd = "spawn_solar_pot"; img = "images/game-icons/pvz/spawn_solar_pot.webp"; type = "plant" },
  @{ name = "Spawn Laser Umbrella"; cmd = "spawn_laser_umbrella"; img = "images/game-icons/pvz/spawn_laser_umbrella.webp"; type = "plant" },
  @{ name = "Spawn Gold Hypno Doom"; cmd = "spawn_gold_hypno_doom"; img = "images/game-icons/pvz/spawn_gold_hypno_doom.webp"; type = "plant" },
  @{ name = "Spawn Pea Sun Flower"; cmd = "spawn_pea_sun_flower"; img = "images/game-icons/pvz/spawn_pea_sun_flower.webp"; type = "plant" },
  @{ name = "Spawn Cherryshooter"; cmd = "spawn_cherryshooter"; img = "images/game-icons/pvz/spawn_cherryshooter.webp"; type = "plant" },
  @{ name = "Spawn Sun Bomb"; cmd = "spawn_sun_bomb"; img = "images/game-icons/pvz/spawn_sun_bomb.webp"; type = "plant" },
  @{ name = "Spawn Cherry Nut"; cmd = "spawn_cherry_nut"; img = "images/game-icons/pvz/spawn_cherry_nut.webp"; type = "plant" },
  @{ name = "Spawn Pea Nut"; cmd = "spawn_pea_nut"; img = "images/game-icons/pvz/spawn_pea_nut.webp"; type = "plant" },
  @{ name = "Spawn Super Cherry Shooter"; cmd = "spawn_super_cherry_shooter"; img = "images/game-icons/pvz/spawn_super_cherry_shooter.webp"; type = "plant" },
  @{ name = "Spawn Sun Nut"; cmd = "spawn_sun_nut"; img = "images/game-icons/pvz/spawn_sun_nut.webp"; type = "plant" },
  @{ name = "Spawn Pea Mine"; cmd = "spawn_pea_mine"; img = "images/game-icons/pvz/spawn_pea_mine.webp"; type = "plant" },
  @{ name = "Spawn Double Cherry"; cmd = "spawn_double_cherry"; img = "images/game-icons/pvz/spawn_double_cherry.webp"; type = "plant" },
  @{ name = "Spawn Sun Mine"; cmd = "spawn_sun_mine"; img = "images/game-icons/pvz/spawn_sun_mine.webp"; type = "plant" },
  @{ name = "Spawn Potato Nut"; cmd = "spawn_potato_nut"; img = "images/game-icons/pvz/spawn_potato_nut.webp"; type = "plant" },
  @{ name = "Spawn Pea Chomper"; cmd = "spawn_pea_chomper"; img = "images/game-icons/pvz/spawn_pea_chomper.webp"; type = "plant" },
  @{ name = "Spawn Nut Chomper"; cmd = "spawn_nut_chomper"; img = "images/game-icons/pvz/spawn_nut_chomper.webp"; type = "plant" },

  # Photo 5 (121-150)
  @{ name = "Spawn Super Chomper"; cmd = "spawn_super_chomper"; img = "images/game-icons/pvz/spawn_super_chomper.webp"; type = "plant" },
  @{ name = "Spawn Sun Chomper"; cmd = "spawn_sun_chomper"; img = "images/game-icons/pvz/spawn_sun_chomper.webp"; type = "plant" },
  @{ name = "Spawn Potato Chomper"; cmd = "spawn_potato_chomper"; img = "images/game-icons/pvz/spawn_potato_chomper.webp"; type = "plant" },
  @{ name = "Spawn Cherry Chomper"; cmd = "spawn_cherry_chomper"; img = "images/game-icons/pvz/spawn_cherry_chomper.webp"; type = "plant" },
  @{ name = "Spawn Cherry Gatling"; cmd = "spawn_cherry_gatling"; img = "images/game-icons/pvz/spawn_cherry_gatling.webp"; type = "plant" },
  @{ name = "Spawn Pea Puff"; cmd = "spawn_pea_puff"; img = "images/game-icons/pvz/spawn_pea_puff.webp"; type = "plant" },
  @{ name = "Spawn Double Puff"; cmd = "spawn_double_puff"; img = "images/game-icons/pvz/spawn_double_puff.webp"; type = "plant" },
  @{ name = "Spawn Iron Pea"; cmd = "spawn_iron_pea"; img = "images/game-icons/pvz/spawn_iron_pea.webp"; type = "plant" },
  @{ name = "Spawn Puff Nut"; cmd = "spawn_puff_nut"; img = "images/game-icons/pvz/spawn_puff_nut.webp"; type = "plant" },
  @{ name = "Spawn Hypno Puff"; cmd = "spawn_hypno_puff"; img = "images/game-icons/pvz/spawn_hypno_puff.webp"; type = "plant" },
  @{ name = "Spawn Hypno Fume"; cmd = "spawn_hypno_fume"; img = "images/game-icons/pvz/spawn_hypno_fume.webp"; type = "plant" },
  @{ name = "Spawn Scaredy Hypno"; cmd = "spawn_scaredy_hypno"; img = "images/game-icons/pvz/spawn_scaredy_hypno.webp"; type = "plant" },
  @{ name = "Spawn Scared Fume"; cmd = "spawn_scared_fume"; img = "images/game-icons/pvz/spawn_scared_fume.webp"; type = "plant" },
  @{ name = "Spawn Super Hypno"; cmd = "spawn_super_hypno"; img = "images/game-icons/pvz/spawn_super_hypno.webp"; type = "plant" },
  @{ name = "Spawn Tall Nut Football"; cmd = "spawn_tall_nut_football"; img = "images/game-icons/pvz/spawn_tall_nut_football.webp"; type = "plant" },
  @{ name = "Spawn Iron Nut"; cmd = "spawn_iron_nut"; img = "images/game-icons/pvz/spawn_iron_nut.webp"; type = "plant" },
  @{ name = "Spawn Double Shooer"; cmd = "spawn_double_shooer"; img = "images/game-icons/pvz/spawn_double_shooer.webp"; type = "plant" },
  @{ name = "Spawn Sun Shroom"; cmd = "spawn_sun_shroom"; img = "images/game-icons/pvz/spawn_sun_shroom.webp"; type = "plant" },
  @{ name = "Spawn Gatling Pea"; cmd = "spawn_gatling_pea"; img = "images/game-icons/pvz/spawn_gatling_pea.webp"; type = "plant" },
  @{ name = "Spawn Twin Flower"; cmd = "spawn_twin_flower"; img = "images/game-icons/pvz/spawn_twin_flower.webp"; type = "plant" },
  @{ name = "Spawn Snow Pea Shooter"; cmd = "spawn_snow_pea_shooter"; img = "images/game-icons/pvz/spawn_snow_pea_shooter.webp"; type = "plant" },
  @{ name = "Spawn Ice Puff"; cmd = "spawn_ice_puff"; img = "images/game-icons/pvz/spawn_ice_puff.webp"; type = "plant" },
  @{ name = "Spawn Small Ice Shroom"; cmd = "spawn_small_ice_shroom"; img = "images/game-icons/pvz/spawn_small_ice_shroom.webp"; type = "plant" },
  @{ name = "Spawn Ice Fume Shroom"; cmd = "spawn_ice_fume_shroom"; img = "images/game-icons/pvz/spawn_ice_fume_shroom.webp"; type = "plant" },
  @{ name = "Spawn Ice Scaredy Shroom"; cmd = "spawn_ice_scaredy_shroom"; img = "images/game-icons/pvz/spawn_ice_scaredy_shroom.webp"; type = "plant" },
  @{ name = "Spawn Tall Ice Nut"; cmd = "spawn_tall_ice_nut"; img = "images/game-icons/pvz/spawn_tall_ice_nut.webp"; type = "plant" },
  @{ name = "Spawn Ice Doom"; cmd = "spawn_ice_doom"; img = "images/game-icons/pvz/spawn_ice_doom.webp"; type = "plant" },
  @{ name = "Spawn Ice Hypno"; cmd = "spawn_ice_hypno"; img = "images/game-icons/pvz/spawn_ice_hypno.webp"; type = "plant" },
  @{ name = "Spawn Scaredy Doom"; cmd = "spawn_scaredy_doom"; img = "images/game-icons/pvz/spawn_scaredy_doom.webp"; type = "plant" },
  @{ name = "Spawn Doom Fume"; cmd = "spawn_doom_fume"; img = "images/game-icons/pvz/spawn_doom_fume.webp"; type = "plant" }
)

$missing = @()
$found = 0
foreach ($item in $s2eItems) {
    $p = $item.img -replace '/', '\'
    if (Test-Path $p) {
        $found++
    } else {
        # Try matching without spawn_ or without underscores
        $c = Get-ChildItem "images\game-icons\pvz" -Filter "*$($item.cmd -replace '_','')*"
        if ($c) {
            $item.img = "images/game-icons/pvz/$($c[0].Name)"
            $found++
        } else {
            $missing += $item.name
        }
    }
}

Write-Output "Tested 150 Reference Items -> Found: $found, Missing: $($missing.Count)"
if ($missing.Count -gt 0) {
    Write-Output "Missing items: $($missing -join ', ')"
}
